/* ─────────────────────────────────────────────────────────
   TICKER + BOOT-SEQUENCE TEXT
   Extracted verbatim from the original app.js. Values unchanged.
───────────────────────────────────────────────────────── */

export const TICKER_MSGS = [
  'OPERATION REBIRTH: ACTIVE · TIER-3 TO CEO MINDSET ENGAGED',
  'PROJECT INDRA-AI: 94% CV PRECISION ON TRANSMISSION FAULTS',
  'FLOWSYNC-AI: 12 INTERSECTIONS OPTIMIZED · WAIT-TIME REDUCTION ACHIEVED',
  'VYUHA: CLASSIFIED DIRECTIVE · DECENTRALIZED SWARM LOGIC ACTIVE',
  'DEFENSE AI ARCHIVE: DAILY CI/CD COMPLETE · DATA PIPELINES NOMINAL',
  'A.V.A.T.A.R: EDGE-AI KINEMATIC PIPELINE · 60FPS TARGET · WASM: NOMINAL',
  'PROMPTLY AI: 3X THROUGHPUT OPTIMIZED · LIABILITY AUDIT: ACTIVE',
  'THREAT ASSESSMENT: ELEVATED · SWARM PROTOCOL ON STANDBY · CITADEL: SECURE',
  'ALL OPERATIVES CLEAR · HAR HAR MAHADEV · CODERUDRA-X: ACTIVE',
];

// Boot Sequence log lines
export const BLINES = [
  '> INITIALIZING COMMAND CENTER OS v10.0...',
  '> OPERATION REBIRTH: VERIFIED',
  '> DECRYPTING 6 MAIN PORTFOLIO SECTORS...',
  '> AUTH: CLEARANCE LVL-5 GRANTED',
  '> AI SUBSYSTEMS: ALL NOMINAL',
  '> TERRAIN DATABASE: LOADED',
  '> SWARM PROTOCOL: STANDBY',
  '> HAR HAR MAHADEV — OPERATIVE VERIFIED ■',
  '> DROP ZONE LOCKED · AWAITING ORDER...',
];
